name: Remove old branches in gh-pages

on:
  workflow_call:
  workflow_dispatch:
jobs:
  Call-Sushi :
    runs-on: ubuntu-latest

    steps:
      - name: Delete old branches
        run: |
          git status
          branches=()
          for branch in $(git for-each-ref --format='%(refname)' refs/heads/); do branches+="${branch#"refs/heads/"}"; done
          echo $branches
          git checkout gh-pages
          for dossier in ig; do [[ ! " $branches " =~ " ${dossier%/} " ]] && echo "Suppression $dossier" && rm -r "$dossier"; done
# for d in ig ; do echo "$d"; done